### ISSUE TITLE
Add animal: Cat

### ISSUE THREAD

**Issue by ro-fldr** [KFU-DATB31UB-24W/animal-fun-facts#9]
Request to add `cat.md` to `facts/` and subsequently adding following fact: 
"Contrary to popular belief, cats indeed have only one life". 
Source: [Wikipedia](https://en.wikipedia.org/wiki/Cat#Superstitions_and_rituals) - 27.11.2024 @ 16:45

**Comment by behackl** [comment]
Good one, should be added for sure!
